### ISSUE TITLE
Attempting to index a nil value

### ISSUE THREAD

**Issue by byronpendason** [OXY2DEV/termNvim#1]
On a fresh install of Neovim, I installed this repo and got the following errors on the first run:

```
Error detected while processing UIEnter Autocommands for "*":
Error executing lua callback: ...are/nvim/lazy/spaceport.nvim/lua/spaceport/screens/r.lua:46: attempt to index a nil value
stack traceback:
        ...are/nvim/lazy/spaceport.nvim/lua/spaceport/scree
ns/r.lua:46: in function 'screenLines'
        .../share/nvim/lazy/spaceport.nvim/lua/spaceport/sc
reen.lua:376: in function 'renderGrid'
        .../share/nvim/lazy/spaceport.nvim/lua/spaceport/sc
reen.lua:551: in function 'render'
        ...re/nvim/lazy/spaceport.nvim/lua/spaceport/setup_
auto.lua:108: in function <...re/nvim/lazy/spaceport.nvim/lua/spaceport/setup_auto.lua:101>
```

**Comment by OXY2DEV** [comment]
This repository is unmaintained. Apologies for the inconveniences.

The plugin in question(`spaceport.nvim`) probably updated. This repo was used by me for Neovim 0.8 & 0.9.5.

So, most of the stuff is outdated. If you want to see my dotfiles it's [here](https://github.com/OXY2DEV/nvim).

---

It is not recommended to use this repo as it's *unfit* for regular use(slow loading time & sluggish behavior on relatively large files).
